TIMX-18-marc-transform-additional-fields
MITLibraries/transmogrifier pull request #34
Opened 2022-10-20 15:29 UTC by ehanson8

#### How can a reviewer manually see the effects of these changes?
Run the transform locally using the `alma-2022-10-11-full-extracted-records-to-index.xml` file in the dev S3 bucket, e.g.:

```
pipenv run transform -i <S3 URL for the above file> -o alma-transformed-records.json -s alma
```

#### What are the relevant tickets?
* https://mitlibraries.atlassian.net/browse/TIMX-18

#### Developer
- [x] All new ENV is documented in README
- [x] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer
- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Includes new or updated dependencies?
NO

2022-10-20 15:30 UTC, ehanson8 commented on tests/fixtures/marc/marc_record_all_fields.xml
> +        <datafield tag="111" ind1="2" ind2=" ">
I’ve included a full 111 field from our local data, these (and 711s) seem to be formatted this way in almost all the examples I found so I’m not sure if we want to process this differently than the Go version. The punctuation makes it quirky

2022-10-20 15:31 UTC, ehanson8 commented on transmogrifier/helpers.py
> +def crosswalk_value(crosswalk_path: str, type_value: Optional[str]) -> Optional[str]:
I’m adding this parameter and more specific crosswalk files given the likelihood of overlapping letter codes for other fields but let me know if you see a cleaner approach

2022-10-20 15:32 UTC, ehanson8 commented on tests/test_marc.py
> +                value="Theory of Cryptography Conference 2008 : New York, N.Y",
`rstrip` does have the side effect of removing abbreviation punctuation in some cases

2022-10-21 21:01 UTC, hakbailey reviewed
See inline comments for suggestions. I think the contributors field in particular would be a lot more similar to the records from our other sources with a few small changes.

2022-10-24 12:43 UTC, ehanson8 commented on transmogrifier/sources/marc.py
> +                "kind": "Main Entry - Personal Name",
Agreed, I was having second thoughts about this as I was looking ahead to other fields. I'll pull in the relator and probably also remove the `Main Entry` and `Added Entry` language from alt title

2022-10-24 12:44 UTC, ehanson8 commented on transmogrifier/sources/marc.py
> +                datafield, "agrt", " "
So I'm planning to continue using `create_subfield_value_string_from_datafield` but run a `split` after to turn it into a list, does that seem correct?

2022-10-24 15:45 UTC, ehanson8 commented on tests/test_marc.py
> +            "Célébration : 10 siècles de musique de noël. Language material. "
I agree, I will make a ticket

2022-10-24 15:59 UTC, hakbailey commented on transmogrifier/sources/marc.py
> +                datafield, "agrt", " "
What will you split on? How will you make sure separate subfield tags are split and metadata with separators in a single subfield are also split?

2022-10-24 16:04 UTC, ehanson8 commented on transmogrifier/sources/marc.py
> +                datafield, "agrt", " "
I obviously misinterpreted your comment, let me dig into the data so I better understand

2022-10-24 16:15 UTC, hakbailey commented on transmogrifier/sources/marc.py
> +                datafield, "agrt", " "
Let me know if this seems wrong to you, but I think we want each subfield code entry to be its own item in the list unless the given subfield entry has the ` -- ` separator, in which case each item between the separator should be its own item in the list. We need to allow for the possibility of either case.

2022-10-24 16:32 UTC, ehanson8 commented on transmogrifier/sources/marc.py
> +                datafield, "agrt", " "
This all makes sense, I'm tracking now. Mondays 🙃

2022-10-24 19:40 UTC, ehanson8 commented on tests/test_marc.py
> +                value="Theory of Cryptography Conference 2008 : New York, N.Y",
I redid the contributor `rstrip`, I don't think it's possible to clean up the `711`s without messing up the `700`s and `710`s so I'm prioritizing the formatting of those 2 given the infrequency of the `711`. I also added `rstrip` to `contents` which I think makes it more readable but let me know your thoughts

2022-10-25 18:29 UTC, hakbailey requested changes
See a few suggestions/questions inline, once we get the contributors in line with our other sources this should be good to go.

2022-10-25 18:29 UTC, hakbailey commented on tests/test_marc.py
> +                kind="composer, performer",
We're also going to need to think about deduping contributors, right now there are a lot of records where the same contributor (with the same `value` and `kind`) is listed more than once.

2022-10-25 18:45 UTC, ehanson8 commented on transmogrifier/sources/marc.py
> +                "kind": "Uniform Title",
I like it!

2022-10-25 18:52 UTC, ehanson8 commented on transmogrifier/sources/marc.py
> +                "agrt",
👍

2022-10-25 19:08 UTC, ehanson8 commented on transmogrifier/helpers.py
> +    if value in crosswalk_dict:
There is not!

2022-10-26 15:04 UTC, ehanson8 commented on tests/test_marc.py
> +                kind="composer, performer",
Updated the code to add separate contributors for each kind value and dedupe before setting the `fields` value. I tried to streamline a somewhat involved process as much as possible, see if I missed anything

2022-10-27 21:24 UTC, hakbailey approved these changes
Looks good!

2022-10-27 21:39 UTC, merged