Rdi 53 zenodo transform
MITLibraries/transmogrifier pull request #6
Opened 2022-05-12 18:04 UTC by ehanson8

#### Helpful background context
JPAL records don't require any parsing of identifiers for the `source_link` so I don't think a JPAL subclass is necessary at this point but let me know if you think differently.

#### How can a reviewer manually see the effects of these changes?
Apologies for continuing to stall this discussion, let's discuss when we reengage with the project 

#### What are the relevant tickets?
https://mitlibraries.atlassian.net/browse/RDI-53

#### Developer
- [x] All new ENV is documented in README
- [x] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer
- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Includes new or updated dependencies?
NO

2022-05-12 22:04 UTC, hakbailey requested changes
One important change: we need to add `zenodo` to the cli `--source` choices, and update the cli logic to handle that source. Other non-blocking suggestions inline and below.

A general comment: we could simplify the fixtures by combining all of the `relatedItemIdentifier` types into a single fixture that just has multiple relatedItems. Same for the `nameIdentifie`r types. It looks like you've updated the `all_fields` fixture to include all the variations anyway, so we could even just use that and reduce the need for so many extra fixtures.

2022-05-13 12:53 UTC, ehanson8 commented on transmogrifier/sources/datacite.py
> +            and i.attrs["relationType"] in ["IsIdenticalTo", "IsVersionOf"]
I think we should remove it here, I agree about the potential for confusion and that `isIdenticalTo` should remain. I'll update the tests

2022-05-13 13:32 UTC, ehanson8 commented
Good call on the fixtures, I fleshed out the `all_fields` fixture and removed the redundant ones

2022-05-16 14:32 UTC, hakbailey approved these changes
One non-blocking cleanup suggestion inline, but this looks good!

2022-05-16 15:12 UTC, merged